### ISSUE TITLE
error: type 'LAPolicy' has no member 'deviceOwnerAuthenticationWithBiometricsOrCompanion'

### ISSUE THREAD

**Issue by linkarzu** [Logicer16/pam-watchid#2]
Hey there, hope you're having a great day!
- I'm trying to configure sudo authentication with my mac mini `without` touch ID, I'm only trying to use my apple watch
- As per [this conversation](https://github.com/biscuitehh/pam-watchid/issues/26#issuecomment-2448603025) that should be possible
- however, I'm getting the following error even after the commit that applied 2 days ago.
```bash
linkarzu.@.mini~/github/pam-watchid on  main via 🐦 v5.10 took 8s
[24/11/01] kubernetes ()
❯ sudo make install
swiftc watchid-pam-extension.swift  -DSEQUOIASDK -o pam_watchid_x86_64.so -target x86_64-apple-darwin23.6.0 -emit-library
watchid-pam-extension.swift:85:21: error: type 'LAPolicy' has no member 'deviceOwnerAuthenticationWithBiometricsOrCompanion'
            return .deviceOwnerAuthenticationWithBiometricsOrCompanion
                   ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [all] Error 1
```
- I'm running macOS Sonoma 14.6.1
- Computer I'm using is a mac mini M1
- Just to add a bit more context, if I turn on my external magic keyboard with touch ID, authentication with my apple watch works using this config 
  - but I'm trying to leave the magic keyboard out, as that is not my main keyboard and I don't want to have it turned on just to have touch ID enabled
```bash
linkarzu.@.mini/etc/pam.d🔒
[24/11/01] kubernetes ()
❯ cat sudo
# sudo: auth account password session
auth       include        sudo_local
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so

linkarzu.@.mini/etc/pam.d🔒
[24/11/01] kubernetes ()
❯ cat sudo_local
# sudo_local: local config file which survives system update and is included for sudo
# uncomment following line to enable Touch ID for sudo
auth       optional       /opt/homebrew/lib/pam/pam_reattach.so
auth       sufficient     pam_tid.so
```

- Could you please let me know if I'm missing something?
- If you need any other details to troubleshoot, please let me know and I'll be more than happy to provide any relevant info
- Again, thanks for taking time out of your day to look at this, appreciate it

**Comment by mostpinkest** [comment]
Hi again!

Just so I can try to reproduce it, can I get you to run the following commands so I can get your configured Xcode and macOS SDK versions:

```sh
xcodebuild -version
xcrun --sdk macosx --show-sdk-path
```

**Comment by linkarzu** [comment]
I don't have `Xcode` installed, just `xcode-select` as ~it~ brew required it for the Command Line Tools (CLT)

```bash
linkarzu.@.mini~
[24/11/04] kubernetes ()
❯ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

linkarzu.@.mini~
[24/11/04] kubernetes ()
❯ xcrun --sdk macosx --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

linkarzu.@.mini~
[24/11/04] kubernetes ()
❯ xcode-select -version
xcode-select version 2409.
```

Do I need to have xcode installed?

**Comment by linkarzu** [comment]
By the way, I upgraded to Sequoia yesterday, so I'm in macOS `Sequoia 15.1`

**Comment by mostpinkest** [comment]
Alright, this *should* (fingers crossed) be fixed now.

The issue lied in Apple structuring their SDKs differently for the CLT and Xcode. Xcode has versioned symlinks to unversioned folders:

```
% ls -lah /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
total 0
drwxr-xr-x  5 user  staff   160B 10 Sep 22:15 .
drwxr-xr-x  6 user  staff   192B 29 Aug 06:43 ..
drwxr-xr-x  7 user  staff   224B 10 Sep 22:12 MacOSX.sdk
lrwxr-xr-x  1 user  staff    10B 10 Sep 22:12 MacOSX15.0.sdk -> MacOSX.sdk
lrwxr-xr-x  1 user  staff    10B 10 Sep 22:12 MacOSX15.sdk -> MacOSX.sdk
```

Whereas, the CLT has unversioned symlinks to versioned folders:

```
% ls -lah /Library/Developer/CommandLineTools/SDKs
total 0
drwxr-xr-x  7 root  wheel   224B 31 Oct 18:21 .
drwxr-xr-x  6 root  wheel   192B 25 Oct 18:03 ..
lrwxr-xr-x  1 root  wheel    14B 31 Oct 18:21 MacOSX.sdk -> MacOSX15.1.sdk
drwxr-xr-x  7 root  wheel   224B  8 Jul 18:09 MacOSX14.5.sdk
lrwxr-xr-x  1 root  wheel    14B 31 Oct 18:20 MacOSX14.sdk -> MacOSX14.5.sdk
drwxr-xr-x  7 root  wheel   224B 11 Oct 10:11 MacOSX15.1.sdk
lrwxr-xr-x  1 root  wheel    14B 31 Oct 18:20 MacOSX15.sdk -> MacOSX15.1.sdk
```

As of https://github.com/Logicer16/pam-watchid/commit/f97da3f7c9ba4bae925561e4baf3dd88c9e47447, the makefile now checks for both.

Seen as you've updated though, you probably won't be experiencing this issue anymore regardless.

**Comment by linkarzu** [comment]
You're a genius, my magic keyboard is off now, and I get the authentication notications on my apple watch when using my mac mini

![linkarzu com 2024-11-05 at 10 43 41](https://github.com/user-attachments/assets/2c046b5b-9bab-4e6b-b134-491041af7fdd)

In case anyone else is wondering, here's what my files look like
```bash
linkarzu.@.mini/etc/pam.d🔒 took 3s
[24/11/05] kubernetes ()
❯ cat sudo
# sudo: auth account password session
auth       include        sudo_local
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so

linkarzu.@.mini/etc/pam.d🔒
[24/11/05] kubernetes ()
❯ cat sudo_local
# sudo_local: local config file which survives system update and is included for sudo
# uncomment following line to enable Touch ID for sudo
auth       optional       /opt/homebrew/lib/pam/pam_reattach.so
auth       sufficient     pam_watchid.so
auth       sufficient     pam_tid.so
```

I really appreciate all your help and time troubleshooting this!

**Comment by linkarzu** [comment]
I created a video on how to set all of this up in case someone is interested
- [Link to my video with the entire setup process here](https://youtu.be/Ddb0viKux9A)
- [If you don't like videos, link to my blogpost here](https://linkarzu.com/posts/macos/auth-apple-watch/)

<div align="center">
    <a href="https://youtu.be/Ddb0viKux9A" target="_blank">
       <img src="https://github.com/user-attachments/assets/737f1095-c4b4-4f15-bca7-6ca35e70933c" width="500">
    </a>
</div>
