### ISSUE TITLE
Lines in `sudo_local` are duplicated if already present

### ISSUE THREAD

**Issue by mostpinkest** [Logicer16/pam-watchid#3]
As per https://linkarzu.com/posts/macos/auth-apple-watch/#installation-with-script:

```
linkarzu.@.mini/etc/pam.d🔒 took 4s
[24/11/10] kubernetes ()
❯ cat sudo_local
# sudo_local: local config file which survives system update and is included for sudo
# uncomment following line to enable Touch ID for sudo
auth optional /opt/homebrew/lib/pam/pam_reattach.so
auth sufficient pam_watchid.so
auth       sufficient     pam_tid.so
# sudo_local: local config file which survives system update and is included for sudo
# uncomment following line to enable Touch ID for sudo
auth       sufficient     pam_tid.so
auth sufficient pam_watchid.so
```

**Comment by mostpinkest** [comment]
@linkarzu Seen as this was originally prompted by your blog post, thought I'd let you know it's been fixed now.

**Comment by linkarzu** [comment]
Appreciate the tag @Logicer16, so quick question then, let's say I'm following my guide, it will not add the extra lines at the bottom of the file, and it also won't touch my `pam_reattach.so` or other existing config?

**Comment by mostpinkest** [comment]
When modifying `sudo_local`, it should preserve all other lines and will no longer add *duplicate* lines. This means that if `pam_watchid.so` is already present anywhere in the file, no change will be made.

All it requires is the `pam_tid.so` line be present anywhere in the file. This is so the `pam_watchid.so` line can be "anchored" somewhere in the file. If it's not present, no change is made as to not break the rest of your config.

For example, If you start with:

```
# sudo_local: local config file which survives system update and is included for sudo
auth optional /opt/homebrew/lib/pam/pam_reattach.so
# uncomment following line to enable Touch ID for sudo
# auth       sufficient     pam_tid.so
```

Your resulting config should be:

```
# sudo_local: local config file which survives system update and is included for sudo
auth optional /opt/homebrew/lib/pam/pam_reattach.so
# uncomment following line to enable Touch ID for sudo
auth       sufficient     pam_tid.so
auth sufficient pam_watchid.so
```
